version: '3.8'

services:
  mysql:
    image: mysql:5.6
    container_name: imy-mysql
    environment:
      MYSQL_ROOT_PASSWORD: ''
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_DATABASE: feedback_db
      MYSQL_USER: mb23005
      MYSQL_PASSWORD: '12345'
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-config:/etc/mysql/conf.d
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --sql-mode=NO_ENGINE_SUBSTITUTION
      - --bind-address=0.0.0.0  # Принимаем подключения со всех интерфейсов
      - --skip-name-resolve  # Ускоряем подключения, отключаем DNS-проверки
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 10s
      retries: 5

volumes:
  mysql_data: